In [1]:
import numpy as np

In [8]:
np.linspace(0,2,11)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [9]:
np.linspace(2,5,7)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [4]:
np.linspace(5,10,6)

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [5]:
x = list(np.array(range(0,20,1))/10)
x = x[:-1]
x+= list(np.array(range(4,10,1))/2)
x = x[:-1]
x+= range(5,10,1)
x = np.array(x)
print(x)
        
k = [1, 0.9092, 0.8341, 0.7711, 0.7177, 0.6720, 0.6320, 0.5970, 0.5659, 0.5384, 0.5136, 0.4914, 0.4711]
k+= [0.4527, 0.4359, 0.4205, 0.4062, 0.3931, 0.3809, 0.3695, 0.3589, 0.3146, 0.2807, 0.2537, 0.2316]
k+= [0.2131, 0.1973, 0.1719, 0.1523, 0.1367, 0.1240, 0.1135]
k = np.array(k)
        
ans = dict(zip(x, k))
ans[0.3]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 2.  2.5 3.  3.5 4.  5.  6.  7.  8.  9. ]


0.7711

In [6]:
x = list(np.array(range(0,20,1))/10)
x[3]

0.3

In [7]:
x = [element for element in x]
x[3]

0.3